# create a toml file with the following content
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "star-emg"
version = "0.0.1"
authors = [
  { name="Amedeo ceglia", email="amedeo.ceglia@umontreal.ca" },
]
description = "Package for Stimulation Artifact Removal in EMG during transcutaneous spinal stimulation."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = ["numpy", "scipy", "matplotlib"]

[project.urls]
"Homepage" = "https://github.com/aceglia/star-emg"
"Bug Tracker" = "https://github.com/aceglia/star-emg/issues"
